config {
  type: "table",
  database: "sterlingx-insights",
  schema: "firm_marketing_localbrandmanager",
  name: "sterlinglawyers_localbrandmanager_review_management",
  tags: ["local brand manager", "review management", "marketing data", "sterlinglawyers"]
}

WITH reviews AS (
  SELECT
    TIMESTAMP(JSON_VALUE(raw_json, '$.created_at')) AS created_at,
    TIMESTAMP(JSON_VALUE(raw_json, '$.deleted_at')) AS deleted_at,

    JSON_VALUE(raw_json, '$.location_name') AS location_name,
    JSON_VALUE(raw_json, '$.location_place_id') AS location_place_id,

    SAFE_CAST(JSON_VALUE(raw_json, '$.rating') AS INT64) AS rating,

    JSON_VALUE(raw_json, '$.remote_id') AS remote_id,
    JSON_VALUE(raw_json, '$.remote_location_id') AS remote_location_id,

    JSON_VALUE(raw_json, '$.reply') AS reply,

    -- Nested reviewer object
    JSON_VALUE(raw_json, '$.reviewer.display_name') AS reviewer_display_name,
    JSON_VALUE(raw_json, '$.reviewer.profile_photo_url') AS reviewer_profile_photo_url,

    JSON_VALUE(raw_json, '$.text') AS review_text,

    TIMESTAMP(JSON_VALUE(raw_json, '$.updated_at')) AS updated_at
  FROM rc-datamart-adminreport.local_brand_manager.raw_lbm_gmb_reviews
)

, location AS 
(
      SELECT
    JSON_VALUE(raw_json, '$.address') AS address,
    JSON_VALUE(raw_json, '$.administrative_area') AS administrative_area,
    JSON_VALUE(raw_json, '$.city') AS city,
    JSON_VALUE(raw_json, '$.country') AS country,
    TIMESTAMP(JSON_VALUE(raw_json, '$.created_at')) AS created_at,
    SAFE_CAST(JSON_VALUE(raw_json, '$.enabled') AS BOOL) AS enabled,
    TIMESTAMP(JSON_VALUE(raw_json, '$.enabled_at')) AS enabled_at,
    JSON_VALUE(raw_json, '$.gbp_id') AS gbp_id,
    JSON_VALUE(raw_json, '$.gmb_url') AS gmb_url,
    JSON_VALUE(raw_json, '$.id') AS id,
    TIMESTAMP(JSON_VALUE(raw_json, '$.keywords_synced_at')) AS keywords_synced_at,
    SAFE_CAST(JSON_VALUE(raw_json, '$.lat') AS FLOAT64) AS lat,
    SAFE_CAST(JSON_VALUE(raw_json, '$.lng') AS FLOAT64) AS lng,
    JSON_VALUE(raw_json, '$.name') AS name,
    JSON_VALUE(raw_json, '$.note') AS note,
    JSON_VALUE(raw_json, '$.phone_number') AS phone_number,
    JSON_VALUE(raw_json, '$.place_id') AS place_id,
    JSON_VALUE(raw_json, '$.postal_code') AS postal_code,
    JSON_VALUE(raw_json, '$.primary_category') AS primary_category,
    JSON_VALUE(raw_json, '$.source_type') AS source_type,
    JSON_VALUE(raw_json, '$.store_code') AS store_code,
    JSON_VALUE(raw_json, '$.website_url') AS website_url,

    -- Arrays
    JSON_VALUE_ARRAY(raw_json, '$.additional_categories') AS additional_categories,
    JSON_VALUE_ARRAY(raw_json, '$.labels') AS labels,
    JSON_VALUE_ARRAY(raw_json, '$.states') AS states,
    JSON_VALUE_ARRAY(raw_json, '$.tags') AS tags,

    -- Object
    JSON_QUERY(raw_json, '$.regular_hours') AS regular_hours
  FROM rc-datamart-adminreport.local_brand_manager.raw_lbm_locations
)

SELECT 
   '99584197-537f-4cf5-80b4-29c99205f07a' AS SterlingX_Client_ID,
   'Sterling Lawyers' AS SterlingX_Client_Name,
    l.id AS location_id,
    l.name AS location_name,
    l.address AS lcoation_address,
    COUNT(remote_id) as total_reviews,
    AVG(rating) as avg_rating,
    COUNTIF(
        DATE(r.created_at) >= DATE_TRUNC(CURRENT_DATE(), MONTH)
        AND DATE(r.created_at) < DATE_ADD(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 1 MONTH)
    ) AS no_of_new_reviews
FROM reviews r
JOIN location l ON r.remote_location_id = l.gbp_id
WHERE r.remote_location_id IN (
     '4876512664995594122'
    , '16988969063393048795'
    , '10931099594657774584'
    , '17941127118439768684'
    , '13531510631738134831'
    , '14646822855372261133'
    , '1198548561503145186'
    , '6858040208639926663'
    , '9919966450102188044'
    , '8160932924768578989'
    , '1645279597686279172'
    , '6577667559421203233'
    , '12171599193743387943'
    , '3440709950703370770'
    , '14718246423358305580'
    , '17447151546318891169'
    , '10198566356960489103'
    , '191700818976737223'
    , '204513130701930716'
    , '4601293684255119974'
    , '18384725598315924870'
    , '6729021868639229871'
    , '16459152869499502168'
    , '15802488226651876518'
    , '15612511989459461984'
    , '3408750892119490739'
    , '17215640466676370349'
    , '12113806508722348267'
    , '7921814686502296195'
)
  AND deleted_at IS NULL
GROUP BY l.id,
    l.name,
    l.address





