config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "omnipress_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "omnipress"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_omnipress.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '1a402c5a-b3e7-4fc6-9f2e-cbd4c5ffe02a' AS SterlingX_Client_ID,
  'Omnipress' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance