config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "omnipress_googlesearchconsole_search_performance",
    tags: ["google search console", "search performance", "omnipress"],
}

SELECT
  '1a402c5a-b3e7-4fc6-9f2e-cbd4c5ffe02a' AS SterlingX_Client_ID,
  'Omnipress' AS SterlingX_Client_Name,

  data_date,
  site_url,
  query,

  clicks,
  impressions,
  position,
FROM `rc-datamart-adminreport.google_search_console_omnipress.fct_gsc_query_metrics`
ORDER BY 
data_date DESC,
query ASC
