config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleanalytics4",
    name: "gjesdahllaw_googleanalytics4_session_organic",
    tags: ["google analytics 4", "ga4", "session organic", "marketing data", "gjesdahllaw"],
}

SELECT
  '17c0939a-2e3d-4728-933d-564183626ec3' AS SterlingX_Client_ID,
  'Gjesdahl Law' AS SterlingX_Client_Name,
    fa.property_id,
    fa.event_date,
    -- dimensions
    JSON_VALUE(fa.dimension_values_json, '$.date') AS date,
    JSON_VALUE(fa.dimension_values_json, '$.sessionPrimaryChannelGroup') AS sessionPrimaryChannelGroup,

    -- metrics
    SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.sessions') AS INT64) AS sessions,
    SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.engagedSessions') AS INT64) AS engaged_sessions,
FROM `rc-datamart-adminreport.google_analytics4_gjesdahllaw.fact_ga4_daily_analysis` fa
LEFT JOIN `rc-datamart-adminreport.google_analytics4_gjesdahllaw.dim_ga4_report` dr
    ON fa.report_id = dr.report_id
WHERE dr.report_category = 'traffic_acquisition'
    AND dr.report_name = 'session_organic_daily'
    -- Exclude all channels containing "Paid"
    AND LOWER(
        COALESCE(
            JSON_VALUE(
                fa.dimension_values_json,
                '$.sessionPrimaryChannelGroup'
            ),
            ''
        )
    ) NOT LIKE '%paid%'
    -- Exclude Referral
    AND LOWER(
        COALESCE(
            JSON_VALUE(
                fa.dimension_values_json,
                '$.sessionPrimaryChannelGroup'
            ),
            ''
        )
    ) NOT LIKE '%referral%'

