config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "moranwealth_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "moranwealth"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_moranwealth.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '2cdee080-147c-4540-9a80-18a0835d2c0d' AS SterlingX_Client_ID,
  'Moran Wealth Management' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance