config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleads",
    name: "porcellolawoffices_googleads_quality_score",
    tags: ["google ads", "quality score", "marketing data", "porcellolawoffices"],
}

SELECT
  '6e2f5f01-f691-4603-8f7d-d5644a5bbb0e' AS SterlingX_Client_ID,
  'Porcello Law Offices' AS SterlingX_Client_Name,
    qs.customer_id,
    dc.customer_name,
    qs.campaign_id,
    cp.campaign_name,
    qs.keyword_text,
    qs.keyword_match_type,
    qs.segment_date,
    qs.quality_score,
    qs.quality_score_landing_page,
    qs.quality_score_ad_relevance,
    qs.quality_score_ctr
FROM `rc-datamart-adminreport.google_ads_porcellolawoffices.fct_gads_keyword_quality_score_daily` qs
LEFT JOIN `rc-datamart-adminreport.google_ads_porcellolawoffices.dim_gads_customer` dc
    ON qs.customer_id = dc.customer_id
LEFT JOIN `rc-datamart-adminreport.google_ads_porcellolawoffices.dim_gads_campaign` cp
    ON qs.campaign_id = cp.campaign_id
