config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "haffnerlaw_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "haffnerlaw"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_test_haffnerlaw.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  date,
  impressions,
  clicks

FROM website_performance