config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "fivestarbodies_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "fivestarbodies"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_fivestarbodies.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  'd990f128-e1bb-4467-b6c9-2e52317ba7ed' AS SterlingX_Client_ID,
  'Five Star Bodies' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance