config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "fivestarbodies_googlesearchconsole_search_performance",
    tags: ["google search console", "search performance", "fivestarbodies"],
}

SELECT
  'd990f128-e1bb-4467-b6c9-2e52317ba7ed' AS SterlingX_Client_ID,
  'Five Star Bodies' AS SterlingX_Client_Name,

  data_date,
  site_url,
  query,

  clicks,
  impressions,
  position,
FROM `rc-datamart-adminreport.google_search_console_fivestarbodies.fct_gsc_query_metrics`
ORDER BY 
data_date DESC,
query ASC
