config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "ireland_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "ireland"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_ireland.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  'a9b10ec7-4dfe-4058-bdb5-a53e66176eed' AS SterlingX_Client_ID,
  'Michael Ireland & Associates' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance