config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "johnsonlaw_googlesearchconsole_search_performance",
    tags: ["google search console", "search performance", "johnsonlaw"],
}

SELECT
  '0c4e2f26-cf3d-41e3-978f-8cd31726062f' AS SterlingX_Client_ID,
  'Johnson Law Group' AS SterlingX_Client_Name,

  data_date,
  site_url,
  query,

  clicks,
  impressions,
  position,
FROM `rc-datamart-adminreport.google_search_console_johnsonlaw.fct_gsc_query_metrics`
ORDER BY 
data_date DESC,
query ASC
