config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "blattnerfamilylaw_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "blattnerfamilylaw"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_blattnerfamilylaw.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '66588887-f466-46e0-9650-b94e9f9801cf' AS SterlingX_Client_ID,
  'Blattner Family Law Group' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance