config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "servicecreditunion_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "servicecreditunion"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_servicecreditunion.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  'dfb1117c-1e5f-462a-8c0e-5977a216dc5c' AS SterlingX_Client_ID,
  'Service Credit Union' AS SterlingX_Client_Name,
  date,
  impressions,
  clicks

FROM website_performance