config {
  type: "table",
  database: "sterlingx-insights",
  schema: "firm_marketing_localbrandmanager",
  name: "blattnerfamilylaw_localbrandmanager_gbp_performance",
  tags: ["local brand manager", "gbp performance", "marketing data", "blattnerfamilylaw"]
}


WITH performance_metric AS
(
  SELECT
  JSON_VALUE(raw_json, '$._lbm_gbp_id') AS lbm_gbp_id,
  JSON_VALUE(raw_json, '$._lbm_location_record_id') AS lbm_location_record_id,
  JSON_VALUE(raw_json, '$._lbm_performance_location_id') AS lbm_performance_location_id,
  JSON_VALUE(raw_json, '$._lbm_place_id') AS lbm_place_id,

  SAFE_CAST(JSON_VALUE(raw_json, '$.timestamp') AS DATE) AS timestamp,
  SAFE_CAST(JSON_VALUE(raw_json, '$.business_direction_requests') AS INT64) AS business_direction_requests,
  SAFE_CAST(JSON_VALUE(raw_json, '$.business_impressions_desktop_maps') AS INT64) AS business_impressions_desktop_maps,
  SAFE_CAST(JSON_VALUE(raw_json, '$.business_impressions_desktop_search') AS INT64) AS business_impressions_desktop_search,
  SAFE_CAST(JSON_VALUE(raw_json, '$.business_impressions_mobile_maps') AS INT64) AS business_impressions_mobile_maps,
  SAFE_CAST(JSON_VALUE(raw_json, '$.business_impressions_mobile_search') AS INT64) AS business_impressions_mobile_search,
  SAFE_CAST(JSON_VALUE(raw_json, '$.call_clicks') AS INT64) AS call_clicks,
  SAFE_CAST(JSON_VALUE(raw_json, '$.website_clicks') AS INT64) AS website_clicks
FROM rc-datamart-adminreport.local_brand_manager.raw_lbm_performance_metrics
)

, location AS 
(
      SELECT
    JSON_VALUE(raw_json, '$.address') AS address,
    JSON_VALUE(raw_json, '$.administrative_area') AS administrative_area,
    JSON_VALUE(raw_json, '$.city') AS city,
    JSON_VALUE(raw_json, '$.country') AS country,
    TIMESTAMP(JSON_VALUE(raw_json, '$.created_at')) AS created_at,
    SAFE_CAST(JSON_VALUE(raw_json, '$.enabled') AS BOOL) AS enabled,
    TIMESTAMP(JSON_VALUE(raw_json, '$.enabled_at')) AS enabled_at,
    JSON_VALUE(raw_json, '$.gbp_id') AS gbp_id,
    JSON_VALUE(raw_json, '$.gmb_url') AS gmb_url,
    JSON_VALUE(raw_json, '$.id') AS id,
    TIMESTAMP(JSON_VALUE(raw_json, '$.keywords_synced_at')) AS keywords_synced_at,
    SAFE_CAST(JSON_VALUE(raw_json, '$.lat') AS FLOAT64) AS lat,
    SAFE_CAST(JSON_VALUE(raw_json, '$.lng') AS FLOAT64) AS lng,
    JSON_VALUE(raw_json, '$.name') AS name,
    JSON_VALUE(raw_json, '$.note') AS note,
    JSON_VALUE(raw_json, '$.phone_number') AS phone_number,
    JSON_VALUE(raw_json, '$.place_id') AS place_id,
    JSON_VALUE(raw_json, '$.postal_code') AS postal_code,
    JSON_VALUE(raw_json, '$.primary_category') AS primary_category,
    JSON_VALUE(raw_json, '$.source_type') AS source_type,
    JSON_VALUE(raw_json, '$.store_code') AS store_code,
    JSON_VALUE(raw_json, '$.website_url') AS website_url,

    -- Arrays
    JSON_VALUE_ARRAY(raw_json, '$.additional_categories') AS additional_categories,
    JSON_VALUE_ARRAY(raw_json, '$.labels') AS labels,
    JSON_VALUE_ARRAY(raw_json, '$.states') AS states,
    JSON_VALUE_ARRAY(raw_json, '$.tags') AS tags,

    -- Object
    JSON_QUERY(raw_json, '$.regular_hours') AS regular_hours
  FROM rc-datamart-adminreport.local_brand_manager.raw_lbm_locations
)

SELECT
   '66588887-f466-46e0-9650-b94e9f9801cf' AS SterlingX_Client_ID,
   'Blattner Family Law Group' AS SterlingX_Client_Name,
   timestamp,
    l.id AS location_id,
    l.name AS location_name,
    l.address AS lcoation_address,
    business_impressions_desktop_maps,
    business_impressions_desktop_search,
    business_impressions_mobile_maps,
    business_impressions_mobile_search,
    business_direction_requests,
    call_clicks,
    website_clicks    
FROM performance_metric pm
JOIN location l ON pm.lbm_location_record_id = l.id
WHERE pm.lbm_location_record_id = 'el4gdjkl'
--   and timestamp between '2026-08-08' and '2026-08-14'