config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleads",
    name: "neuroendo_googleads_localserviceads",
    tags: ["google ads", "local service ads", "marketing data", "neuroendo"],
}

WITH cte_local_service_ads AS
(
  SELECT
    d.customer_id,
    dc.customer_name,
    d.segment_date AS date,
    (d.cost_micros / 1000000.0) AS cost,
    d.conversions
  FROM `rc-datamart-adminreport.google_ads_neuroendo.fct_gads_campaign_daily` d
  JOIN `rc-datamart-adminreport.google_ads_neuroendo.dim_gads_campaign` c
    ON d.campaign_id = c.campaign_id
  LEFT JOIN `rc-datamart-adminreport.google_ads_neuroendo.dim_gads_customer` dc
    ON d.customer_id = dc.customer_id
  WHERE c.advertising_channel_type = 'LOCAL_SERVICES'
)

SELECT
  'c469e634-8986-4161-9b8e-b8d38b5fd826' AS SterlingX_Client_ID,
  'NeuroEndoMKE' AS SterlingX_Client_Name,
  customer_id,
  customer_name,
  date,
  SUM(cost) AS cost,
  SUM(conversions) AS conversions,
  IFNULL(SAFE_DIVIDE(SUM(cost), SUM(conversions)), 0.0) AS cpl
FROM cte_local_service_ads
GROUP BY ALL
