config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "ramagelaw_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "ramagelaw"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_ramagelaw.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
   'f3e5ceb5-3957-4541-a076-f51d3dd4cec5' AS SterlingX_Client_ID,
   'The Ramage Law Group' AS SterlingX_Client_Name,
  date,
  impressions,
  clicks

FROM website_performance