config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "ramagelaw_googlesearchconsole_key_query_performance",
    tags: ["google search console", "key query performance", "ramagelaw"],
}

WITH key_query_performance AS (

  SELECT
    data_date AS date,
    query,

    -- Total impressions
    SUM(impressions) AS impressions,

    -- Additive numerator for GSC Average Position
    SUM(
      CASE
        WHEN position IS NOT NULL
        THEN position * impressions
        ELSE 0
      END
    ) AS position_weighted_sum,

    -- Additive denominator for GSC Average Position
    SUM(
      CASE
        WHEN position IS NOT NULL
        THEN impressions
        ELSE 0
      END
    ) AS position_weighted_impressions

  FROM
    `rc-datamart-adminreport.google_search_console_ramagelaw.fct_gsc_key_query_performance`

  GROUP BY
    data_date,
    query
)

SELECT
   'f3e5ceb5-3957-4541-a076-f51d3dd4cec5' AS SterlingX_Client_ID,
   'The Ramage Law Group' AS SterlingX_Client_Name,
  date,
  query,

  -- Daily/query position
  SAFE_DIVIDE(
    position_weighted_sum,
    position_weighted_impressions
  ) AS position,

  impressions,

  -- Keep these for correct aggregation across dates/queries
  position_weighted_sum,
  position_weighted_impressions

FROM key_query_performance