config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "porcellolawoffices_googlesearchconsole_search_performance",
    tags: ["google search console", "search performance", "porcellolawoffices"],
}

SELECT
  '6e2f5f01-f691-4603-8f7d-d5644a5bbb0e' AS SterlingX_Client_ID,
  'Porcello Law Offices' AS SterlingX_Client_Name,

  data_date,
  site_url,
  query,

  clicks,
  impressions,
  position,
FROM `rc-datamart-adminreport.google_search_console_porcellolawoffices.fct_gsc_query_metrics`
ORDER BY 
data_date DESC,
query ASC
