config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "fanashfamily_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "fanashfamily"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_fanashfamily.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '8a4bb5d3-2988-4b58-901a-d7ebdb015a10' AS SterlingX_Client_ID,
  'Fanash Family Law' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance