config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "sterlinglawyers_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "sterlinglawyers"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_sterlinglawyers.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '99584197-537f-4cf5-80b4-29c99205f07a' AS SterlingX_Client_ID,
  'Sterling Lawyers' AS SterlingX_Client_Name,
  date,
  impressions,
  clicks

FROM website_performance