config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "elkussisson_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "elkussisson"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_elkussisson.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
    'b861c480-0aa3-4af5-a7c7-6081e9623458' AS SterlingX_Client_ID,
    'Elkus & Sisson' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance