config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleanalytics4",
    name: "fivestarbodies_googleanalytics4_custom_events",
    tags: ["google analytics 4", "ga4", "custom events", "marketing data", "fivestarbodies"],
}

SELECT
  'd990f128-e1bb-4467-b6c9-2e52317ba7ed' AS SterlingX_Client_ID,
  'Five Star Bodies' AS SterlingX_Client_Name,
    fa.property_id,
    fa.event_date,
    -- dimensions
    JSON_VALUE(fa.dimension_values_json, '$.date') AS date,
    JSON_VALUE(fa.dimension_values_json, '$.eventName') AS event_name,
    JSON_VALUE(fa.dimension_values_json, '$.firstUserPrimaryChannelGroup') AS first_user_primary_channel_group,
    -- metrics
    SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.eventCount') AS INT64) AS event_count
FROM `rc-datamart-adminreport.google_analytics4_fivestarbodies.fact_ga4_daily_analysis` fa
LEFT JOIN `rc-datamart-adminreport.google_analytics4_fivestarbodies.dim_ga4_report` dr
    ON fa.report_id = dr.report_id
WHERE dr.report_category = 'events'
    AND dr.report_name = 'custom_events_daily'
