config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "lancasterlaw_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "lancasterlaw"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_lancasterlaw.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '331dae6a-d0e7-48fe-866e-b068ec98059e' AS SterlingX_Client_ID,
  'Lancaster' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance