config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleanalytics4",
    name: "lancasterlaw_googleanalytics4_organic",
    tags: ["google analytics 4", "ga4", "organic", "marketing data", "lancasterlaw"],
}

SELECT
  '331dae6a-d0e7-48fe-866e-b068ec98059e' AS SterlingX_Client_ID,
  'Lancaster' AS SterlingX_Client_Name,
    fa.property_id,
    fa.event_date,
    -- dimensions
    JSON_VALUE(fa.dimension_values_json, '$.date') AS date,
    JSON_VALUE(fa.dimension_values_json, '$.firstUserPrimaryChannelGroup') AS firstUserPrimaryChannelGroup,

    -- metrics
    SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.newUsers') AS INT64) AS newUsers,
    -- SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.engagedSessions') AS INT64) AS engaged_sessions,
FROM `rc-datamart-adminreport.google_analytics4_lancasterlaw.fact_ga4_daily_analysis` fa
LEFT JOIN `rc-datamart-adminreport.google_analytics4_lancasterlaw.dim_ga4_report` dr
    ON fa.report_id = dr.report_id
WHERE dr.report_category = 'user_acquisition' 
    AND dr.report_name = 'organic_daily'
    -- Exclude all channels containing "Paid"
    AND LOWER(
        COALESCE(
            JSON_VALUE(
                fa.dimension_values_json,
                '$.firstUserPrimaryChannelGroup'
            ),
            ''
        )
    ) NOT LIKE '%paid%'
    -- Exclude Referral
    AND LOWER(
        COALESCE(
            JSON_VALUE(
                fa.dimension_values_json,
                '$.firstUserPrimaryChannelGroup'
            ),
            ''
        )
    ) NOT LIKE '%referral%'

