config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleanalytics4",
    name: "neuroendo_googleanalytics4_custom_events",
    tags: ["google analytics 4", "ga4", "custom events", "marketing data", "neuroendo"],
}

SELECT
  'c469e634-8986-4161-9b8e-b8d38b5fd826' AS SterlingX_Client_ID,
  'NeuroEndoMKE' AS SterlingX_Client_Name,
    fa.property_id,
    fa.event_date,
    -- dimensions
    JSON_VALUE(fa.dimension_values_json, '$.date') AS date,
    JSON_VALUE(fa.dimension_values_json, '$.eventName') AS event_name,
    JSON_VALUE(fa.dimension_values_json, '$.firstUserPrimaryChannelGroup') AS first_user_primary_channel_group,
    -- metrics
    SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.eventCount') AS INT64) AS event_count
FROM `rc-datamart-adminreport.google_analytics4_neuroendo.fact_ga4_daily_analysis` fa
LEFT JOIN `rc-datamart-adminreport.google_analytics4_neuroendo.dim_ga4_report` dr
    ON fa.report_id = dr.report_id
WHERE dr.report_category = 'events'
    AND dr.report_name = 'custom_events_daily'
