config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "cutrerlaw_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "cutrerlaw"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_cutrerlaw.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
    '2e0efe10-f122-4a03-bfa5-7215e2dd7b71' AS SterlingX_Client_ID,
    'Cutrer' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance