config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "cutrerlaw_googlesearchconsole_search_performance",
    tags: ["google search console", "search performance", "cutrerlaw"],
}

SELECT
    '2e0efe10-f122-4a03-bfa5-7215e2dd7b71' AS SterlingX_Client_ID,
    'Cutrer' AS SterlingX_Client_Name,

  data_date,
  site_url,
  query,

  clicks,
  impressions,
  position,
FROM `rc-datamart-adminreport.google_search_console_cutrerlaw.fct_gsc_query_metrics`
ORDER BY 
data_date DESC,
query ASC
