config {
  type: "view",
  database: "rc-datamart-adminreport",
  schema: "sterling_lawyers", 
  name: "stg_sl_google_ads_old_lsa", 
  tags: ["google_ads", "sterling lawyers"]
}

/*
  Changelog: yyyy-mm-dd jbatoy: 
*/

SELECT
  date
  , campaign
  , clicks
  , spend
  , conversions
FROM ${ref("google_ads_data")}
WHERE customer_id IN (
    '5788001493'
    , '4848705759'
    , '5543903899'
    , '2530434917'
    , '5137010586'
  )