config {
  type: "view",
  database: "rc-datamart-adminreport",
  schema: "sterling_lawyers", 
  name: "stg_sterling_lawyers_stackadapt", 
  tags: ["stackadapt", "sterling lawyers"]
}

/*
  Changelog: yyyy-mm-dd jbatoy: 
*/

SELECT
  granularity_date AS date
  , campaign_name AS campaign
  , clicks
  , cost AS spend
  , conversions
  , impressions
FROM `rc-datamart-adminreport.sterling_lawyers.stackadapt_campaign_delivery`