config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleanalytics4",
    name: "ireland_googleanalytics4_session_organic",
    tags: ["google analytics 4", "ga4", "session organic", "marketing data", "ireland"],
}

SELECT
  'a9b10ec7-4dfe-4058-bdb5-a53e66176eed' AS SterlingX_Client_ID,
  'Michael Ireland & Associates' AS SterlingX_Client_Name,
    fa.property_id,
    fa.event_date,
    -- dimensions
    JSON_VALUE(fa.dimension_values_json, '$.date') AS date,
    JSON_VALUE(fa.dimension_values_json, '$.sessionPrimaryChannelGroup') AS sessionPrimaryChannelGroup,

    -- metrics
    SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.sessions') AS INT64) AS sessions,
    SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.engagedSessions') AS INT64) AS engaged_sessions,
FROM `rc-datamart-adminreport.google_analytics4_ireland.fact_ga4_daily_analysis` fa
LEFT JOIN `rc-datamart-adminreport.google_analytics4_ireland.dim_ga4_report` dr
    ON fa.report_id = dr.report_id
WHERE dr.report_category = 'traffic_acquisition'
    AND dr.report_name = 'session_organic_daily'
