config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "hicksfamilylawyers_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "hicksfamilylawyers"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_hicksfamilylawyers.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '41406391-4166-4c73-ab0a-db73d34a18dd' AS SterlingX_Client_ID,
  'Hicks Family Lawyers' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance