config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "neuroendo_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "neuroendo"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_neuroendo.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  'c469e634-8986-4161-9b8e-b8d38b5fd826' AS SterlingX_Client_ID,
  'NeuroEndoMKE' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance