config {
  type: "table",
  database: "rc-datamart-adminreport",
  schema: "analytics_vasquez_de_lara", 
  name: "fct_vdl_pagespeed_insights", 
  tags: ["pagespeed_insights", "vdl", "vasquez de lara"]
}

/*
  Changelog: 2025-11-21 jbatoy: include only specific fields.
*/

SELECT
  date
  , strategy
  , performance_score
FROM ${ref("rc-datamart-adminreport","vasquez_de_lara","stg_vdl_pagespeed_insights")}
ORDER BY date
