config {
  type: "table",
  database: "rc-datamart-adminreport",
  schema: "analytics_vasquez_de_lara", 
  name: "fct_vdl_stackadapt", 
  tags: ["stackadapt", "vdl", "vasquez de lara"]
}

/*
  Changelog: 2025-11-21 jbatoy: include only specific fields.
*/

SELECT
  date
  , campaign
  , clicks
  , spend
  , conversions
  , impressions
FROM ${ref("rc-datamart-adminreport","vasquez_de_lara","stg_vdl_stackadapt")}
ORDER BY date
