config {
  type: "table",
  database: "rc-datamart-adminreport",
  schema: "analytics_vasquez_de_lara", 
  name: "fct_vdl_call_rail", 
  tags: ["call_rail", "vdl", "vasquez de lara"]
}

/*
  Changelog: 2025-11-21 jbatoy: include only specific fields.
*/

SELECT 
  date
  , source_name
  , direction
  , answered
  , medium
FROM ${ref("rc-datamart-adminreport","vasquez_de_lara","stg_vdl_call_rail")}
ORDER BY date


