config {
  type: "table",
  database: "rc-datamart-adminreport",
  schema: "analytics_vasquez_de_lara", 
  name: "fct_vdl_google_search_console", 
  tags: ["google_search_console", "vdl", "vasquez de lara"]
}

/*
  Changelog: 2025-11-21 jbatoy: include only specific fields.
*/

SELECT
  date
  , impressions
  , clicks
FROM ${ref("rc-datamart-adminreport","vasquez_de_lara","stg_vdl_google_search_console")}
ORDER BY date
