config {
  type: "table",
  database: "rc-datamart-adminreport",
  schema: "analytics_vasquez_de_lara", 
  name: "fct_vdl_facebook_ads", 
  tags: ["facebook_ads", "vdl", "vasquez de lara"]
}

/*
  Changelog: 2025-11-21 jbatoy: include only specific fields.
*/

SELECT 
  date
  , campaign
  , clicks
  , spend
  , actions_offsite_conversion_fb_pixel_custom
  , impressions
FROM ${ref("rc-datamart-adminreport","vasquez_de_lara","stg_vdl_facebook_ads")}
ORDER BY date
