config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "lisavance_googlesearchconsole_search_performance",
    tags: ["google search console", "search performance", "lisavance"],
}

SELECT
  '84daafc1-503c-47e2-8fed-410f56f64a96' AS SterlingX_Client_ID,
  'Lisa Vance' AS SterlingX_Client_Name,

  data_date,
  site_url,
  query,

  clicks,
  impressions,
  position,
FROM `rc-datamart-adminreport.google_search_console_lisavance.fct_gsc_query_metrics`
ORDER BY 
data_date DESC,
query ASC
