config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "lisavance_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "lisavance"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_lisavance.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '84daafc1-503c-47e2-8fed-410f56f64a96' AS SterlingX_Client_ID,
  'Lisa Vance' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance