config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleanalytics4",
    name: "bankfivenine_googleanalytics4_custom_users",
    tags: ["google analytics 4", "ga4", "custom users", "marketing data", "bankfivenine"],
}

SELECT
  'eb3cb793-c3ea-4476-90f5-702c1b421f17' AS SterlingX_Client_ID,
  'Bank Five Nine' AS SterlingX_Client_Name,
    fa.property_id,
    fa.event_date,
    -- dimensions
    JSON_VALUE(fa.dimension_values_json, '$.date') AS date,
    -- metrics
    SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.totalUsers') AS INT64) AS event_count
FROM `rc-datamart-adminreport.google_analytics4_bankfivenine.fact_ga4_daily_analysis` fa
LEFT JOIN `rc-datamart-adminreport.google_analytics4_bankfivenine.dim_ga4_report` dr
    ON fa.report_id = dr.report_id
WHERE dr.report_category = 'users'
    AND dr.report_name = 'custom_users_daily'
