config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "bankfivenine_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "bankfivenine"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_bankfivenine.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  'eb3cb793-c3ea-4476-90f5-702c1b421f17' AS SterlingX_Client_ID,
  'Bank Five Nine' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance