config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "bankfivenine_googlesearchconsole_search_performance",
    tags: ["google search console", "search performance", "bankfivenine"],
}

SELECT
  'eb3cb793-c3ea-4476-90f5-702c1b421f17' AS SterlingX_Client_ID,
  'Bank Five Nine' AS SterlingX_Client_Name,

  data_date,
  site_url,
  query,

  clicks,
  impressions,
  position,
FROM `rc-datamart-adminreport.google_search_console_bankfivenine.fct_gsc_query_metrics`
ORDER BY 
data_date DESC,
query ASC
