config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleanalytics4",
    name: "porcellolawoffices_googleanalytics4_custom_users",
    tags: ["google analytics 4", "ga4", "custom users", "marketing data", "porcellolawoffices"],
}

SELECT
  '6e2f5f01-f691-4603-8f7d-d5644a5bbb0e' AS SterlingX_Client_ID,
  'Porcello Law Offices' AS SterlingX_Client_Name,
    fa.property_id,
    fa.event_date,
    -- dimensions
    JSON_VALUE(fa.dimension_values_json, '$.date') AS date,
    -- metrics
    SAFE_CAST(JSON_VALUE(fa.metric_values_json, '$.totalUsers') AS INT64) AS event_count
FROM `rc-datamart-adminreport.google_analytics4_porcellolawoffices.fact_ga4_daily_analysis` fa
LEFT JOIN `rc-datamart-adminreport.google_analytics4_porcellolawoffices.dim_ga4_report` dr
    ON fa.report_id = dr.report_id
WHERE dr.report_category = 'users'
    AND dr.report_name = 'custom_users_daily'
