config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "gjesdahllaw_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "gjesdahllaw"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_gjesdahllaw.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '17c0939a-2e3d-4728-933d-564183626ec3' AS SterlingX_Client_ID,
  'Gjesdahl Law' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance