config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "gjesdahllaw_googlesearchconsole_search_performance",
    tags: ["google search console", "search performance", "gjesdahllaw"],
}

SELECT
  '17c0939a-2e3d-4728-933d-564183626ec3' AS SterlingX_Client_ID,
  'Gjesdahl Law' AS SterlingX_Client_Name,

  data_date,
  site_url,
  query,

  clicks,
  impressions,
  position,
FROM `rc-datamart-adminreport.google_search_console_gjesdahllaw.fct_gsc_query_metrics`
ORDER BY 
data_date DESC,
query ASC
