config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "meyerpinklaw_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "meyerpinklaw"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_meyerpinklaw.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '5537c7d2-eb93-4748-bc6a-e236641db089' AS SterlingX_Client_ID,
  'Meyer Pink' AS SterlingX_Client_Name,

  date,
  impressions,
  clicks

FROM website_performance