config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googlesearchconsole",
    name: "theonefamilylaw_googlesearchconsole_website_performance",
    tags: ["google search console", "website performance", "theonefamilylaw"],
}

WITH website_performance AS (

  SELECT
    data_date AS date,
    SUM(impressions) AS impressions,
    SUM(clicks) AS clicks

  FROM
    `rc-datamart-adminreport.google_search_console_theonefamilylaw.fct_gsc_website_performance`

  GROUP BY
    data_date

)

SELECT
  '030e704b-5142-453c-9313-9befd2111b31' AS SterlingX_Client_ID, 
  'The One Family Law' AS SterlingX_Client_Name, 
  date,
  impressions,
  clicks

FROM website_performance