config {
    type: "table",
    database: "sterlingx-insights",
    schema: "firm_marketing_googleads",
    name: "johnsonlaw_googleads_conversion_action_daily",
    tags: ["google ads", "conversion action", "marketing data", "johnsonlaw"],
    bigquery: {
        partitionBy: "segment_date",
        clusterBy: ["customer_id", "campaign_id", "conversion_action_id"]
    }
}

/*
1. When the offline conversion action is primary/included, it should appear in both conversions and all_conversions.
2. When it is secondary/not included, it may appear only in all_conversions and all_conversions_value.


** conversions	          - Number of conversions included in the main Conversions metric, generally actions with include_in_conversions_metric = TRUE, which can be used for conversion-based bidding.
** conversions_value      - Total assigned value of those conversions. This may represent revenue or a configured lead value.
** all_conversions	      - Number of all tracked conversions, including actions excluded from the main Conversions metric, such as secondary conversion actions.
** all_conversions_value  - Total assigned value of all tracked conversions.

*/

SELECT
    '0c4e2f26-cf3d-41e3-978f-8cd31726062f' AS SterlingX_Client_ID,
    'Johnson Law Group' AS SterlingX_Client_Name,

    fc.segment_date,
    fc.customer_id,
    dc.customer_name,

    fc.campaign_id,
    dp.campaign_name,

    fc.conversion_action_id,
    COALESCE(
        dca.conversion_action_name,
        fc.conversion_action_name
    ) AS conversion_action_name,

    dca.conversion_action_status,
    dca.conversion_action_type,

    COALESCE(
        dca.conversion_action_category,
        fc.conversion_action_category
    ) AS conversion_action_category,

    dca.conversion_action_origin,
    dca.primary_for_goal,
    dca.include_in_conversions_metric,

    fc.conversions,
    fc.conversions_value,
    fc.all_conversions,
    fc.all_conversions_value,
    -- fc.view_through_conversions

FROM `rc-datamart-adminreport.google_ads_johnsonlaw.fct_gads_campaign_conversion_action_daily` fc
LEFT JOIN `rc-datamart-adminreport.google_ads_johnsonlaw.dim_gads_customer` dc
    ON fc.customer_id = dc.customer_id
LEFT JOIN `rc-datamart-adminreport.google_ads_johnsonlaw.dim_gads_campaign` dp
    ON fc.customer_id = dp.customer_id
    AND fc.campaign_id = dp.campaign_id
LEFT JOIN `rc-datamart-adminreport.google_ads_johnsonlaw.dim_gads_conversion_action` dca
    ON fc.customer_id = dca.customer_id
    AND fc.conversion_action_id = dca.conversion_action_id
    